apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-docker-app-deployment
  namespace: nv1
  labels:
    app: new-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new-docker-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: new-docker-app
    spec:
      initContainers:
      - name: init-setup
        image: busybox:latest
        command: ['sh', '-c', 'ls; pwd; sleep 10']
        envFrom:
        - configMapRef:
            name: new-docker-app-deployment
      containers:
      - name: new-docker-app
        image: nv1uppalapati.azurecr.io/new_docker-app:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        envFrom:
        - configMapRef:
            name: new-docker-app-deployment
