apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-docker-app-deployment
  namespace: nv1
  labels:
    app: new-docker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-docker-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: new-docker-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - production
      containers:
        - name: new-docker-app
          image: kubeassignment.azurecr.io/new_docker-app:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 8
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: new-docker-app-deployment
                  key: DB_HOST
